# stage 1

FROM node:alpine AS my-app-build-aks
WORKDIR /app
COPY . .
RUN npm install && npm run build

# stage 2

FROM nginx:alpine
COPY --from=my-app-build-aks /app/dist/frontend-aks /usr/share/nginx/html
EXPOSE 80
